"""
GitLab MR에 리뷰 코멘트를 업로드하는 모듈.
인라인 discussion + 요약 노트를 생성한다.
"""

from __future__ import annotations

import logging

from gitlab.v4.objects import ProjectMergeRequest

from review_bot.gitlab.client import GitLabClient, MRInfo
from review_bot.models.issue import ValidatedIssue, Severity

logger = logging.getLogger(__name__)


class GitLabCommenter:
    def __init__(self, client: GitLabClient) -> None:
        self._project = client._project

    def post_review(
        self,
        mr_id: int,
        mr_info: MRInfo,
        issues: list[ValidatedIssue],
    ) -> None:
        """인라인 코멘트 + 요약 노트를 MR에 게시한다."""
        mr: ProjectMergeRequest = self._project.mergerequests.get(mr_id)
        diffs = mr.diffs.list()
        if not diffs:
            logger.warning(f"MR {mr_id}: diff를 찾을 수 없어 코멘트 스킵")
            return

        diff_detail = mr.diffs.get(diffs[0].id)

        # 인라인 코멘트
        for issue in issues:
            self._post_inline_comment(mr, diff_detail, issue)

        # 요약 노트
        self._post_summary(mr, issues)

        logger.info(f"MR {mr_id}: {len(issues)}개 이슈 코멘트 게시 완료")

    def _post_inline_comment(
        self,
        mr: ProjectMergeRequest,
        diff_detail,
        issue: ValidatedIssue,
    ) -> None:
        """diff 특정 줄에 인라인 discussion을 생성한다."""
        try:
            mr.discussions.create({
                "body": issue.format_comment(),
                "position": {
                    "base_sha": diff_detail.base_commit_sha,
                    "start_sha": diff_detail.start_commit_sha,
                    "head_sha": diff_detail.head_commit_sha,
                    "position_type": "text",
                    "new_path": issue.file_path,
                    "old_path": issue.file_path,
                    "new_line": issue.line_number,
                },
            })
            logger.debug(f"인라인 코멘트: {issue.file_path}:{issue.line_number}")
        except Exception:
            # Fallback: 인라인 실패 시 일반 노트로 전환
            logger.warning(
                f"인라인 코멘트 실패, 일반 노트로 전환: "
                f"{issue.file_path}:{issue.line_number}",
                exc_info=True,
            )
            try:
                mr.notes.create({"body": issue.format_comment()})
            except Exception:
                logger.exception(f"일반 노트도 실패: {issue.issue.code}")

    def _post_summary(
        self,
        mr: ProjectMergeRequest,
        issues: list[ValidatedIssue],
    ) -> None:
        """전체 이슈 요약 테이블을 MR 노트로 게시한다."""
        if not issues:
            mr.notes.create({
                "body": "**🤖 Review Bot**: No issues found. LGTM! ✅",
            })
            return

        severity_counts: dict[str, int] = {}
        for issue in issues:
            sev = issue.severity.value
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        lines = [
            "## 🤖 Review Bot Summary",
            "",
            f"Found **{len(issues)}** issue(s):",
        ]

        severity_emoji = {
            "critical": "🚨", "high": "🔴", "medium": "🟡", "low": "🔵",
        }
        for sev in ["critical", "high", "medium", "low"]:
            if sev in severity_counts:
                lines.append(f"- {severity_emoji[sev]} {sev.upper()}: {severity_counts[sev]}")

        lines += [
            "",
            "| # | Severity | File | Issue |",
            "|---|----------|------|-------|",
        ]
        for i, issue in enumerate(issues, 1):
            lines.append(
                f"| {i} | {issue.severity.value.upper()} "
                f"| `{issue.file_path}:{issue.line_number}` "
                f"| {issue.issue.title} |"
            )

        lines += [
            "",
            "<sub>🤖 Generated by review-bot (Claude Agent SDK) "
            "| False Positive 의심 시 무시하세요</sub>",
        ]

        mr.notes.create({"body": "\n".join(lines)})
